version: "3.8"
services:
  app:
    build:
      context: ./app
    ports:
    - 3000:3000
    networks:
    - graphql-server-example
    depends_on:
    - mysql
    restart: on-failure
    container_name: app
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./sample.sql:/docker-entrypoint-initdb.d/sample.sql
    ports:
    - 3306:3306
    networks:
    - graphql-server-example
    container_name: mysql
networks:
  graphql-server-example:
    name: graphql-server-example