version: "3.8"
services:
  nodejs:
    image: node:15-alpine
    networks:
    - graphql-server-example
    depends_on:
    - mysql
    container_name: nodejs
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./sample.sql:/docker-entrypoint-initdb.d/sample.sql
    ports:
    - 3306:3306
    networks:
    - graphql-server-example
    container_name: mysql
networks:
  graphql-server-example:
    name: graphql-server-example